COMPONENTS = 
["Acetaldehyde",
  "Acetamide",
  "Acetic acid",
  "Acetone",
  "Acetonitrile",
  "Aluminium chloride",
  "Aluminium nitrate",
  "Aluminium sulfate",
  "Ammonia",
  "Ammonium acetate",
  "Ammonium carbonate",
  "Ammonium chloride",
  "Ammonium dichromate",
  "Ammonium hydroxide",
  "Ammonium nitrate",
  "Ammonium oxalate",
  "Ammonium sulfate",
  "Antimony(III) chloride",
  "Antimony(V) chloride",
  "Barium chloride",
  "Barium hydroxide",
  "Barium nitrate",
  "Bismuth(III) chloride",
  "Bismuth(III) nitrate",
  "Butan-1-ol",
  "Butyric acid",
  "Cadmium nitrate",
  "Cadmium sulfate",
  "Calcium chloride",
  "Calcium hydroxide",
  "Calcium nitrate",
  "Calcium sulfate",
  "Carbon disulfide",
  "Chloroacetic acid",
  "Chloroauric acid",
  "Chloroform",
  "Chloroplatinic acid",
  "Chromium(III) chloride",
  "Chromium(III) nitrate",
  "Chromium(III) sulfate",
  "Chromium(VI) oxide",
  "Citric acid",
  "Cobalt(II) nitrate",
  "Cobalt(II) sulfate",
  "Copper(I) chloride",
  "Copper(II) chloride",
  "Copper(II) nitrate",
  "Copper(II) sulfate",
  "Dichloroacetic acid",
  "Diethyl ether",
  "Dimethylglyoxime",
  "EDTA, disodium salt",
  "Ethanol",
  "Ethylene glycol",
  "Formaldehyde",
  "Formic acid",
  "Fructose",
  "Glucose",
  "Glycerol",
  "Hexafluorosilicic acid",
  "Hydrazine",
  "Hydrobromic acid",
  "Hydrochloric acid",
  "Hydrocyanic acid",
  "Hydrofluoric acid",
  "Hydrogen peroxide",
  "Hydroiodic acid",
  "Iodic acid",
  "Iron(II) ammonium sulfate",
  "Iron(II) sulfate",
  "Iron(III) chloride",
  "Iron(III) nitrate",
  "Iron(III) sulfate",
  "Isobutanol",
  "Lactic acid",
  "Lactose",
  "Lead(II) acetate",
  "Lead(II) chloride",
  "Lead(II) nitrate",
  "Lead(IV) acetate",
  "Lithium chloride",
  "Magnesium chloride",
  "Magnesium nitrate",
  "Magnesium sulfate",
  "Maleic acid",
  "Malonic acid",
  "Maltose",
  "Manganese(II) chloride",
  "Manganese(II) sulfate",
  "Mannitol",
  "Mercury(II) chloride",
  "Mercury(II) nitrate",
  "Mercury(II) sulfate",
  "Methanol",
  "Methyl acetate",
  "Nickel chloride",
  "Nickel nitrate",
  "Nickel sulfate",
  "Nicotine",
  "Nitric acid",
  "Oxalic acid",
  "Pentan-1-ol",
  "Perchloric acid",
  "Phenol",
  "Phosphoric acid",
  "Potassium bicarbonate",
  "Potassium bromate",
  "Potassium bromide",
  "Potassium carbonate",
  "Potassium chlorate",
  "Potassium chloride",
  "Potassium chromate",
  "Potassium cyanide",
  "Potassium dichromate",
  "Potassium dihydrogen phosphate",
  "Potassium hexacyanoferrate(II)",
  "Potassium hexacyanoferrate(III)",
  "Potassium hydrogen phosphate",
  "Potassium hydroxide",
  "Potassium iodate",
  "Potassium iodide",
  "Potassium nitrate",
  "Potassium nitrite",
  "Potassium permanganate",
  "Potassium sulfate",
  "Potassium sulfite",
  "Potassium tartrate",
  "Potassium thiocyanate",
  "Propan-1-ol",
  "Propan-2-ol",
  "Pyridine",
  "Resorcinol",
  "Saccharose",
  "Silver nitrate",
  "Silver sulfate",
  "Sodium acetate",
  "Sodium arsenate",
  "Sodium bromide",
  "Sodium carbonate",
  "Sodium chlorate",
  "Sodium chloride",
  "Sodium chromate",
  "Sodium citrate",
  "Sodium dichromate",
  "Sodium dihydrogen phosphate",
  "Sodium formate",
  "Sodium hydrogen carbonate",
  "Sodium hydrogen phosphate",
  "Sodium hydrogen tartrate",
  "Sodium hydroxide",
  "Sodium nitrate",
  "Sodium nitrite",
  "Sodium phosphate",
  "Sodium potassium tartrate",
  "Sodium sulfate",
  "Sodium sulfide",
  "Sodium sulfite",
  "Sodium tartrate",
  "Sodium thiosulfate",
  "Strontium chloride",
  "Strontium nitrate",
  "Strontium sulfate",
  "Sulfuric acid",
  "Sulfurous acid",
  "Tartaric acid",
  "Thiourea",
  "Tin(II) chloride",
  "Tin(IV) chloride",
  "Trichloroacetic acid",
  "TRIS",
  "Urea",
  "Urethane",
  "Zinc bromide",
  "Zinc chloride",
  "Zinc nitrate",
  "Zinc sulfate"]

VACCINE_NAMES = [
"CoV2 SAM (LNP) vaccine","A.D.T.","A.K.D.S.","ABDALA - CIGB-66 COVID-19 Vaccine","ABHAYRAB","ABNCoV2","AC VAX","ACEL-IMUNE","ACELLULAR D.P.T. KOVAX","ACT-HIB","ACTACEL","ADACEL","ADACEL POLIO","AFLUNOV","AFLURIA","AGRIFLU","AGRIPPAL","AIMMUGEN","ALDIANA","ALDITEANA","ALDITERPERA","AMARIL","AMBIRIX","AMC","ANADIFTERALL","ANATETALL","AREPANRIX","ARILVAX","ATTENUVAX","AV-COVID-19","AVAC-1, AVA","AVAXIM 160 U","AVAXIM 80 U","AdCLD-CoV19","AdCOVID","AdimrSC-2f","Adjupanrix","Adjuvanted inactivated vaccine against SARS-CoV-2","Adjuvanted protein subunit (RBD)","Alpha-RIX-Tetra","Arcturus-RNA-Covid","B-CAPSA","BBV154","BCG PASTEUR","BEGRIVAC","BEXSERO","BIAVAX","BIAVAX II","BIKEN","BIKEN-HB","BIMMUGEN","BIOTHRAX","BIVIRATEN BERNA","BOOSTAGEN","BOOSTRIX","BOOSTRIXTETRA","BVAC","Batrevac","Boostrix Polio","C.D.T.","CAM-KOVAX","CD.JEVAX","CELLUVAX","CELVAPAN","CENDEVAX","CERTIVA","CERVARIX","CIGB-669","COH04S1","COMIRNATY Pfizer-BioNTech","COMVAX","CONVIDECIA","CORONAVAC","CORVax12","COVAC-1 - COVAC-2","COVAXIN","COVAXIS","COVAXX","COVI-VAC","COVID-19 Vaccine Janssen","COVID-19 inactivated vaccine","COVID-19 mRNA Vaccine BNT162b2","COVID-eVax","COVIGEN","COVISHIELD","COVIVAC","CUREVAC mRNA COVID-19 Vaccine","ChAdV68-S / ChAdV68-S-TCE / SAM-S-TCE / SAM-LNP-S-TCE","Chinese-Ad5-nCoV-covid","Chinese-Anhui-RBD-Dimer-Covid","Chinese-IMB-Inactivated-Covid","Chinese-Inactivated-Vero-Covid","Chinese-Influenza-intranasal-covid","Chinese-PLA-ARN-Covid","Chinese-Recombinant-Sf9-covid","ChulaCov19","Clover-Spike-SCB-2019-Covid","CombAct-HIB","Coronavirus SARS-CoV-2 inactivé","Covid-19/aAPC","Covigenix VAX-001","D.S.D.P.T.","D.T. BIS - RUDIVAX","D.T. COQ MERIEUX","D.T. POLIO MERIEUX","DAPTACEL","DARONRIX","DENGVAXIA","DI TE PER POL IMPFSTOFF","DI-TE-POL","DIF-TET-ALL","DIFTAVAX","DITE ANATOXAL","DITOXIM","DOUBLE ANIGEN B.","DRYVAX","DS-5670a","DT BIS","DT Mérieux","DTCP PASTEUR","DTVax","DTWP","DTaP","DUAL ANTIGEN SII","DUKORAL","DULTAVAX","ECOLARIX","EFLUELDA","EIPV","ENCEPUR","ENGERIX B 10 µg","ENGERIX B 20 µg","EOLARIX","EPAXAL","ERUCOV-VAC","ERVEVAX RA 27/3","EUVAX B","EpiVacCorona","Ervebo","EuCorVac-19","FENDRIX","FLU SHIELD","FLUAD","FLUAD PAEDIATRICS","FLUARIX","FLUENZ","FLUENZ TETRA","FLUKOVAX-PF INJ","FLULAVAL","FLUOGEN","FLUQUADRI","FLUVIRAL","FLUVIRIN","FLUVIRINE","FLUZONE Quadrivalent","FOCETRIA (multidose)","FOCETRIA (unidose)","FOCLIVIA","FSME-IMMUN 0,25 ml Junior","FSME-IMMUN 0.5 ml","FUNED-CEME","FluMist","FluMist Quadrivalent","FluarixTetra","Flucelvax Tetra","Fluzone High-Dose","Fluzone High-Dose Quadrivalent","GARDASIL","GARDASIL 9","GBP510","GENHEVAC B PASTEUR","GLS-5310","GRAd-COV2 COVID-19 Vaccine ReiThera","GRIPGUARD","GUNEVAX","GX-19-DNA-Covid","Globorix","HAVRIX 1 440 U","HAVRIX 360 U","HAVRIX 720 U","HB VAX DNA 10 µg","HBVAXPRO 10 µg","HBVAXPRO 40 µg","HBVAXPRO 5 µg","HBY","HDT-301","HEPA-B INJECTION","HEPATYRIX","HEPAVAX-GENE","HEPLISAV-B","HEPRECOMB","HEPTAVAX B","HEVAC B","HEXACIMA","HEXAVAC","HEXAXIM","HEXYON","HIBERIX","HIBERNA PRODUCTSIX","HIBEST","HIBTITER","HINKUYS KAROKOE","HUMENZA","HUMOTET-ANTI TETANUS","HbOC","Hecolin","IIBR’s recombinant VSV-DeltaG-spike vaccine","IMMU ORR","IMMUGRIP","IMOJEV","IMOVAX","IMOVAX D.T.","IMOVAX GRIPPE","IMOVAX MUMPS","IMOVAX OREILLONS","IMOVAX PAROTIDITIS","IMOVAX POLIO","IMOVAX R.O.R.","IMOVAX RABIES I.D.","IMOVAX RABIES I.M.","IMOVAX RUBEOLA","IMOVAX SARAMPION","IMVANEX","INFANRIX","INFANRIX HEXA","INFANRIX PENTA","INFANRIX POLIO","INFANRIX Polio HIB Nourrissons","INFANRIX-HIB","INFANRIX-IPV","INFANRIXQUINTA","INFANRIXTETRA","INFLU-KOVAX","INFLUENZA HA VACCINE KOVAX","INFLUSPLIT TETRA","INFLUVAC","INTANZA","INTANZA 9 µg","IPAD DT","IPAD POLIO","IPAD T","IPAD TP","IPOL","IPV","ISTIVAC","IXIARO","Immravax","Imperial-College-RNA-Covid","Inactivated Koçak-19 Inaktif Adjuvanl&#305; COVID-19 Vaccine","Inactivated SARS-CoV-2 vaccine FAKHRAVAC (MIVAC)","Influvac Tetra","Inovio-DNA-Covid","JE-VAX","JEEV","KAKSOISROKOTE DUBBELVACCIN","KIKHOSTE-VAKSINE","KINRIX","Kentucky-RBD-Covid","LANCY VAXINA","LAVANTUU TIROKOTE","LIOVAX","LIRUBEL","LIRUGEN","LM - 2 RIT","LM - 3 RIT","LMU-MVA-SARS-2-S-Covid","LTEANAS IMUNA","LV-SMENP-DC vaccine","LYMERIX","LYOVAC ATTENUVAX","LYOVAC MERUVAX","M-M-R II","M-M-RVAXPRO","M-M-Vax","M-MVax","M-R VAX","M-R VAX II","M-VAX","MASERN-IMPFSTOFF SSW","MEASLES","MEASLES VACCINE DK3","MENACTRA","MENAFRIVAC","MENCEVAX","MENCEVAX A","MENINGITEC","MENINVACT","MENINVACTKIT","MENITORIX","MENJUGATE 10 µg","MENJUGATEKIT 10 µg","MENOMUNE","MENOMUNE-A/C/Y/W-135","MENPOVAX 4","MENPOVAX A+C","MENQUADFI","MENVEO","MERUVAX","MERUVAX II","MEVILIN-L","MF59 adjuvanted SARS-CoV-2 Sclamp vaccine","MMR","MONIARIX","MONOVAX","MOPAVAC SEVAC","MOPV","MORBILVAX","MORUBEL","MORUMAN BERNA PRODUCTSNA","MORUPAR","MOSQUIRIX","MOVIVAC","MUMATEN BERNA PRODUCTSNA","MUMPS inactivated","MUMPS live","MUMPSVAX","MUTAGRIP","MV-014-212","MVABEA","Medicago CoVLP COVID-19 Vaccine","Medigen-S-2P-CpH1018-Covid","MenBvac","Menhibrix","MoRu Viraten","Moraten","Moruman"]

